In [16]:
import pandas as pd

In [51]:
data_final = pd.read_csv('datafinal.csv', sep=',')

In [58]:
len(data_final)

606960

In [52]:
cid = pd.read_csv('worldcities.csv', sep=',')
cid['city'] = cid['city'].str.lower()
cid = cid.rename(columns={"city":"City"})

In [53]:
codeList = [
        "BE", "BG", "CZ", "DK", "DE", "EE", "IE", "EL", "ES", "FR", "HR", "IT", "CY",
        "LV", "LT", "LU", "HU", "MT", "NL", "AT", "PL", "PT", "RO", "SI", "SK", "FI",
        "SE", "UK"]
cid_final = cid.loc[cid.iso2.isin(codeList)]
cid_final = cid_final.filter(items=["City", "lat","lng"])

In [60]:
cid_final[cid_final["City"] == "porto"]

       City    lat   lng
1861  porto  41.15 -8.62

In [56]:
datafinal2 = data_final.merge(cid_final, on="City")
datafinal2 = datafinal2.drop(columns=["Unnamed: 0"])

In [57]:
datafinal2

,ID_TA,City,Name,Style,Price Tag,Number of Reviews,Ranking,Review,Rating,Date_Review,Review_length,count,Type_of_Review,lat,lng
0,d11752080,amsterdam,martine of martine's table,french,medium,136.0,1.0,just like home,5.0,2018-01-03,14,1,positive,52.35,4.9166
1,d11752080,amsterdam,martine of martine's table,french,medium,136.0,1.0,a warm welcome to wintry amsterdam,5.0,2018-01-01,34,2,positive,52.35,4.9166
2,d11752080,amsterdam,martine of martine's table,dutch,medium,136.0,1.0,just like home,5.0,2018-01-03,14,1,positive,52.35,4.9166
3,d11752080,amsterdam,martine of martine's table,dutch,medium,136.0,1.0,a warm welcome to wintry amsterdam,5.0,2018-01-01,34,2,positive,52.35,4.9166
4,d11752080,amsterdam,martine of martine's table,european,medium,136.0,1.0,just like home,5.0,2018-01-03,14,1,positive,52.35,4.9166
5,d11752080,amsterdam,martine of martine's table,european,medium,136.0,1.0,a warm welcome to wintry amsterdam,5.0,2018-01-01,34,2,positive,52.35,4.9166
6,d11752080,amsterdam,martine of martine's table,NaN,medium,136.0,1.0,just like home,5.0,2018-01-03,14,1,positive,52.35,4.9166
7,d11752080,amsterdam,martine of martine's table,NaN,medium,136.0,1.0,a warm welcome to wintry amsterdam,5.0,2018-01-01,34,2,positive,52.35,4.9166
8,d693419,amsterdam,de silveren spiegel,dutch,expensive,812.0,2.0,great food and staff,4.5,2018-01-06,20,1,positive,52.35,4.9166
9,d693419,amsterdam,de silveren spiegel,dutch,expensive,812.0,2.0,just perfect,4.5,2018-01-04,12,1,positive,52.35,4.9166
10,d693419,amsterdam,de silveren spiegel,european,expensive,812.0,2.0,great food and staff,4.5,2018-01-06,20,1,positive,52.35,4.9166
11,d693419,amsterdam,de silveren spiegel,european,expensive,812.0,2.0,just perfect,4.5,2018-01-04,12,1,positive,52.35,4.9166
12,d693419,amsterdam,de silveren spiegel,vegetarian friendly,expensive,812.0,2.0,great food and staff,4.5,2018-01-06,20,1,positive,52.35,4.9166
13,d693419,amsterdam,de silveren spiegel,vegetarian friendly,expensive,812.0,2.0,just perfect,4.5,2018-01-04,12,1,positive,52.35,4.9166
14,d693419,amsterdam,de silveren spiegel,gluten free options,expensive,812.0,2.0,great food and staff,4.5,2018-01-06,20,1,positive,52.35,4.9166
15,d693419,amsterdam,de silveren spiegel,gluten free options,expensive,812.0,2.0,just perfect,4.5,2018-01-04,12,1,positive,52.35,4.9166
16,d696959,amsterdam,la rive,mediterranean,expensive,567.0,3.0,satisfaction,4.5,2018-01-04,12,0,neutral,52.35,4.9166
17,d696959,amsterdam,la rive,mediterranean,expensive,567.0,3.0,delicious old school restaurant,4.5,2018-01-04,31,1,positive,52.35,4.9166
18,d696959,amsterdam,la rive,french,expensive,567.0,3.0,satisfaction,4.5,2018-01-04,12,0,neutral,52.35,4.9166
19,d696959,amsterdam,la rive,french,expensive,567.0,3.0,delicious old school restaurant,4.5,2018-01-04,31,1,positive,52.35,4.9166
20,d696959,amsterdam,la rive,international,expensive,567.0,3.0,satisfaction,4.5,2018-01-04,12,0,neutral,52.35,4.9166
21,d696959,amsterdam,la rive,international,expensive,567.0,3.0,delicious old school restaurant,4.5,2018-01-04,31,1,positive,52.35,4.9166
22,d696959,amsterdam,la rive,european,expensive,567.0,3.0,satisfaction,4.5,2018-01-04,12,0,neutral,52.35,4.9166
23,d696959,amsterdam,la rive,european,expensive,567.0,3.0,delicious old school restaurant,4.5,2018-01-04,31,1,positive,52.35,4.9166
24,d1239229,amsterdam,vinkeles,french,expensive,564.0,4.0,true five star dinner,5.0,2017-12-20,21,0,neutral,52.35,4.9166
25,d1239229,amsterdam,vinkeles,french,expensive,564.0,4.0,a superb evening of fine dining hospitali,5.0,2017-12-17,41,2,positive,52.35,4.9166
26,d1239229,amsterdam,vinkeles,european,expensive,564.0,4.0,true five star dinner,5.0,2017-12-20,21,0,neutral,52.35,4.9166
27,d1239229,amsterdam,vinkeles,european,expensive,564.0,4.0,a superb evening of fine dining hospitali,5.0,2017-12-17,41,2,positive,52.35,4.9166
28,d1239229,amsterdam,vinkeles,international,expensive,564.0,4.0,true five star dinner,5.0,2017-12-20,21,0,neutral,52.35,4.9166
29,d1239229,amsterdam,vinkeles,international,expensive,564.0,4.0,a superb evening of fine dining hospitali,5.0,2017-12-17,41,2,positive,52.35,4.9166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429746,d697141,warsaw,puszkin,NaN,medium,3.0,2132.0,closed,2.0,2010-02-04,6,0,neutral,52.25,21.0000
429747,d697141,warsaw,puszkin,NaN,medium,3.0,2132.0,i wanted to go to this restaurant but it i,2.0,2008-05-18,42,0,neutral,52.25,21.0000
429748,d1628820,warsaw,atrio,polish,cheap,2.0,2133.0,the traveller says no,1.0,2010-04-08,21,0,neutral,52.25,21.0000
429749,d1628820,warsaw,atrio,polish,cheap,2.0,2133.0,dont go there,1.0,2010-01-04,13,0,neutral,52.25,21.0000
429750,d1628820,warsaw,atrio,european,cheap,2.0,2133.0,the traveller says no,1.0,2010-04-08,21,0,neutral,52.25,21.0000
429751,d1628820,warsaw,atrio,european,cheap,2.0,2133.0,dont go there,1.0,2010-01-04,13,0,neutral,52.25,21.0000
429752,d1628820,warsaw,atrio,NaN,cheap,2.0,2133.0,the traveller says no,1.0,2010-04-08,21,0,neutral,52.25,21.0000
429753,d1628820,warsaw,atrio,NaN,cheap,2.0,2133.0,dont go there,1.0,2010-01-04,13,0,neutral,52.25,21.0000
429754,d1628820,warsaw,atrio,NaN,cheap,2.0,2133.0,the traveller says no,1.0,2010-04-08,21,0,neutral,52.25,21.0000
429755,d1628820,warsaw,atrio,NaN,cheap,2.0,2133.0,dont go there,1.0,2010-01-04,13,0,neutral,52.25,21.0000
429756,d10680290,warsaw,hummus bar,middle eastern,cheap,2.0,2134.0,just dont,1.0,2016-11-20,9,0,neutral,52.25,21.0000
429757,d10680290,warsaw,hummus bar,israeli,cheap,2.0,2134.0,just dont,1.0,2016-11-20,9,0,neutral,52.25,21.0000
429758,d10680290,warsaw,hummus bar,NaN,cheap,2.0,2134.0,just dont,1.0,2016-11-20,9,0,neutral,52.25,21.0000
429759,d10680290,warsaw,hummus bar,NaN,cheap,2.0,2134.0,just dont,1.0,2016-11-20,9,0,neutral,52.25,21.0000
429760,d12829445,warsaw,hamsa grill restaurant,mediterranean,cheap,0.0,2141.0,poor service terrible taste,1.0,2017-10-11,28,-2,negative,52.25,21.0000
429761,d12829445,warsaw,hamsa grill restaurant,turkish,cheap,0.0,2141.0,poor service terrible taste,1.0,2017-10-11,28,-2,negative,52.25,21.0000
429762,d12829445,warsaw,hamsa grill restaurant,middle eastern,cheap,0.0,2141.0,poor service terrible taste,1.0,2017-10-11,28,-2,negative,52.25,21.0000
429763,d12829445,warsaw,hamsa grill restaurant,tunisian,cheap,0.0,2141.0,poor service terrible taste,1.0,2017-10-11,28,-2,negative,52.25,21.0000
429764,d12982545,warsaw,inspire lounge,international,medium,0.0,2149.0,nice food if you wont mind waiting 25 ho,1.0,2017-11-29,40,1,positive,52.25,21.0000
429765,d12982545,warsaw,inspire lounge,polish,medium,0.0,2149.0,nice food if you wont mind waiting 25 ho,1.0,2017-11-29,40,1,positive,52.25,21.0000
429766,d12982545,warsaw,inspire lounge,european,medium,0.0,2149.0,nice food if you wont mind waiting 25 ho,1.0,2017-11-29,40,1,positive,52.25,21.0000
429767,d12982545,warsaw,inspire lounge,grill,medium,0.0,2149.0,nice food if you wont mind waiting 25 ho,1.0,2017-11-29,40,1,positive,52.25,21.0000
429768,d11890686,warsaw,grill inn,lebanese,medium,2.0,2150.0,get with the times,1.0,2017-09-23,18,0,neutral,52.25,21.0000
429769,d11890686,warsaw,grill inn,mediterranean,medium,2.0,2150.0,get with the times,1.0,2017-09-23,18,0,neutral,52.25,21.0000
429770,d11890686,warsaw,grill inn,turkish,medium,2.0,2150.0,get with the times,1.0,2017-09-23,18,0,neutral,52.25,21.0000
429771,d11890686,warsaw,grill inn,NaN,medium,2.0,2150.0,get with the times,1.0,2017-09-23,18,0,neutral,52.25,21.0000
429772,d9756760,warsaw,szafran - afghan restaurant,indian,cheap,0.0,2151.0,its a normal kebab place,1.0,2016-06-26,24,0,neutral,52.25,21.0000
429773,d9756760,warsaw,szafran - afghan restaurant,middle eastern,cheap,0.0,2151.0,its a normal kebab place,1.0,2016-06-26,24,0,neutral,52.25,21.0000
429774,d9756760,warsaw,szafran - afghan restaurant,persian,cheap,0.0,2151.0,its a normal kebab place,1.0,2016-06-26,24,0,neutral,52.25,21.0000
429775,d9756760,warsaw,szafran - afghan restaurant,afghani,cheap,0.0,2151.0,its a normal kebab place,1.0,2016-06-26,24,0,neutral,52.25,21.0000

In [59]:
datafinal2.to_csv("Tripdata.csv", sep=',')